const employees = [
  {
    employeeNumber: 1,
    firstName: 'John',
    lastName: 'Doe',
    extension: '1234',
    email: 'john@example.com',
    officeCode: 2,
    reportsTo: null,
    jobTitle: 'President',
    roleId: 1,
  },
  {
    employeeNumber: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    extension: '5678',
    email: 'jane@example.com',
    officeCode: 1,
    reportsTo: 1,
    jobTitle: 'Manager',
    roleId: 2,
  },
  {
    employeeNumber: 3,
    firstName: 'David',
    lastName: 'Brown',
    extension: '4321',
    email: 'david@example.com',
    officeCode: 2,
    reportsTo: 2,
    jobTitle: 'Leader',
    roleId: 3,
  },
  {
    employeeNumber: 4,
    firstName: 'Sarah',
    lastName: 'Johnson',
    extension: '8765',
    email: 'sarah@example.com',
    officeCode: 2,
    reportsTo: 2,
    jobTitle: 'Leader',
    roleId: 3,
  },
  {
    employeeNumber: 5,
    firstName: 'Michael',
    lastName: 'Williams',
    extension: '1357',
    email: 'michael@example.com',
    officeCode: 1,
    reportsTo: 3,
    jobTitle: 'Staff',
    roleId: 4,
  },
  {
    employeeNumber: 6,
    firstName: 'Emily',
    lastName: 'Jones',
    extension: '2468',
    email: 'emily@example.com',
    officeCode: 1,
    reportsTo: 3,
    jobTitle: 'Staff',
    roleId: 4,
  },
  {
    employeeNumber: 7,
    firstName: 'William',
    lastName: 'Davis',
    extension: '3690',
    email: 'william@example.com',
    officeCode: 3,
    reportsTo: 4,
    jobTitle: 'Staff',
    roleId: 4,
  },
  {
    employeeNumber: 8,
    firstName: 'Olivia',
    lastName: 'Taylor',
    extension: '2580',
    email: 'olivia@example.com',
    officeCode: 3,
    reportsTo: 4,
    jobTitle: 'Staff',
    roleId: 4,
  },
  {
    employeeNumber: 9,
    firstName: 'John',
    lastName: 'Doe',
    extension: '1234',
    email: 'john@example.com',
    officeCode: 3,
    reportsTo: null,
    jobTitle: 'President',
    roleId: 1,
  },
];

module.exports = employees;
