const customers = [
  {
    customerNumber: 1,
    customerName: 'Van A Nguyen',
    contactLastName: 'Nguyen',
    contactFirstName: 'Van A',
    phone: '0123456789',
    addressLine1: '123 ABC Street',
    addressLine2: '',
    city: 'Ho Chi Minh City',
    state: 'HCM',
    postalCode: '700000',
    country: 'Vietnam',
    salesRepEmployeeNumber: 1,
    creditLimit: 140000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    customerNumber: 2,
    customerName: 'Thi B Tran',
    contactLastName: 'Tran',
    contactFirstName: 'Thi B',
    phone: '0987654321',
    addressLine1: '456 XYZ Street',
    addressLine2: '',
    city: 'Ha Noi',
    state: 'HN',
    postalCode: '100000',
    country: 'Vietnam',
    salesRepEmployeeNumber: 2,
    creditLimit: 120000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    customerNumber: 3,
    customerName: 'Van C Le',
    contactLastName: 'Le',
    contactFirstName: 'Van C',
    phone: '0909123456',
    addressLine1: '789 MNO Street',
    addressLine2: '',
    city: 'Da Nang',
    state: 'DN',
    postalCode: '500000',
    country: 'Vietnam',
    salesRepEmployeeNumber: 3,
    creditLimit: 200000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    customerNumber: 4,
    customerName: 'Thi D Pham',
    contactLastName: 'Pham',
    contactFirstName: 'Thi D',
    phone: '0909123456',
    addressLine1: '789 MNO Street',
    addressLine2: '',
    city: 'Can Tho',
    state: 'CT',
    postalCode: '900000',
    country: 'Vietnam',
    salesRepEmployeeNumber: 1,
    creditLimit: 300000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    customerNumber: 5,
    customerName: 'Van E Hoang',
    contactLastName: 'Hoang',
    contactFirstName: 'Van E',
    phone: '0123456789',
    addressLine1: '123 ABC Street',
    addressLine2: '',
    city: 'Nha Trang',
    state: 'NT',
    postalCode: '650000',
    country: 'Vietnam',
    salesRepEmployeeNumber: 2,
    creditLimit: 150000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    customerNumber: 6,
    customerName: 'Thi F Do',
    contactLastName: 'Do',
    contactFirstName: 'Thi F',
    phone: '0987654321',
    addressLine1: '456 XYZ Street',
    addressLine2: '',
    city: 'Hue',
    state: 'HU',
    postalCode: '580000',
    country: 'Vietnam',
    salesRepEmployeeNumber: 3,
    creditLimit: 180000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    customerNumber: 7,
    customerName: 'Van G Vu',
    contactLastName: 'Vu',
    contactFirstName: 'Van G',
    phone: '0909123456',
    addressLine1: '789 MNO Street',
    addressLine2: '',
    city: 'Hai Phong',
    state: 'HP',
    postalCode: '400000',
    country: 'Vietnam',
    salesRepEmployeeNumber: 1,
    creditLimit: 250000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    customerNumber: 8,
    customerName: 'Thi H Nguyen',
    contactLastName: 'Nguyen',
    contactFirstName: 'Thi H',
    phone: '0909123456',
    addressLine1: '789 MNO Street',
    addressLine2: '',
    city: 'Vung Tau',
    state: 'VT',
    postalCode: '740000',
    country: 'Vietnam',
    salesRepEmployeeNumber: 2,
    creditLimit: 190000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    customerNumber: 9,
    customerName: 'Van I Tran',
    contactLastName: 'Tran',
    contactFirstName: 'Van I',
    phone: '0123456789',
    addressLine1: '123 ABC Street',
    addressLine2: '',
    city: 'Ha Long',
    state: 'HL',
    postalCode: '500000',
    country: 'Vietnam',
    salesRepEmployeeNumber: 3,
    creditLimit: 220000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = customers;
